# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddtoCart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addtoCart(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1512, 882)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("user@email.com")
    self.driver.find_element(By.NAME, "password").click()
    element = self.driver.find_element(By.NAME, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "password").send_keys("123")
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    # Assert user_name is displayed in the page
    user_name = self.driver.find_element(By.CLASS_NAME, "dropbtn").text
    assert "Ignacio" in user_name

    self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(2) td:nth-child(2) #itemImage").click()
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.LINK_TEXT, "CART 1").click()
    self.driver.find_element(By.LINK_TEXT, "Proceed to checkout").click()
  
