# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegister():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_register(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1512, 882)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.LINK_TEXT, "Register here").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("example5@email.com")
    self.driver.find_element(By.ID, "password").send_keys("123")
    self.driver.find_element(By.ID, "cpassword").send_keys("123")
    self.driver.find_element(By.NAME, "firstName").send_keys("Ignacio4")
    self.driver.find_element(By.NAME, "lastName").send_keys("Tsai")
    self.driver.find_element(By.NAME, "address1").send_keys("line1")
    self.driver.find_element(By.NAME, "address2").send_keys("line2")
    self.driver.find_element(By.NAME, "zipcode").click()
    self.driver.find_element(By.NAME, "zipcode").send_keys("1234")
    self.driver.find_element(By.NAME, "city").click()
    self.driver.find_element(By.NAME, "city").send_keys("CABA")
    self.driver.find_element(By.NAME, "state").click()
    self.driver.find_element(By.NAME, "state").send_keys("Bs As")
    self.driver.find_element(By.NAME, "country").send_keys("ARG")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13)").click()
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("example5@email.com")
    self.driver.find_element(By.NAME, "password").click()
    element = self.driver.find_element(By.NAME, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "password").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
  
